ALTER PROFILE default LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE default LIMIT PASSWORD_LIFE_TIME UNLIMITED;
CREATE USER test IDENTIFIED BY test;
GRANT CONNECT TO test;
GRANT CREATE TABLE TO test;
ALTER USER test QUOTA UNLIMITED ON users;
